# Exercise 2.A Fundamentals of pandas

In [1]:
import numpy as np
import pandas as pd

## Series

In [2]:
aa = [1, 2, 3, 4]
ab = (5, 6, 7, 8)
ac = {9, 10, 11, 12}
ad = {'first': 13, 'second': 14, 'third': 15, 'fourth': 16}

In [3]:
ser1 = pd.Series(aa)
ser2 = pd.Series(ab)
ser3 = pd.Series(list(ac))
ser4 = pd.Series(ad)

print(ser1)
print(ser2)
print(ser3)
print(ser4)

0    1
1    2
2    3
3    4
dtype: int64
0    5
1    6
2    7
3    8
dtype: int64
0     9
1    10
2    11
3    12
dtype: int64
first     13
second    14
third     15
fourth    16
dtype: int64

# This causes a TypeError because Series values must be passed as one collection, like a list.
# TypeError message: Series.__init__() takes from 1 to 2 positional arguments but 5 were given
ser5 = pd.Series(17, 18, 19, 20)

## DataFrames from Series

In [4]:
df1 = pd.DataFrame(ser1)
df1

   0
0  1
1  2
2  3
3  4

In [5]:
df1.insert(1, "ser2", ser2)
df1.insert(2, "ser3", ser3)

df1

   0  ser2  ser3
0  1     5     9
1  2     6    10
2  3     7    11
3  4     8    12

df1.insert(3, "ser4", ser4)

# ser4 was created from a dictionary, so its index labels are words instead of 0, 1, 2, 3.
# Because the labels do not match df1's numeric index, pandas cannot line the values up and returns NaN.

df1

In [22]:
df1

   0  ser2  ser3  ser4
0  1     5     9   NaN
1  2     6    10   NaN
2  3     7    11   NaN
3  4     8    12   NaN
4  5     9    12   0.0

In [23]:
df1["ser4"] = ser4
df1

   0  ser2  ser3  ser4
0  1     5     9   NaN
1  2     6    10   NaN
2  3     7    11   NaN
3  4     8    12   NaN
4  5     9    12   NaN

In [24]:
df1.loc[4] = [5, 9, 12, 0]
df1

   0  ser2  ser3  ser4
0  1     5     9   NaN
1  2     6    10   NaN
2  3     7    11   NaN
3  4     8    12   NaN
4  5     9    12   0.0

In [25]:
df2 = pd.read_csv("sakila_example.csv")

df2
df2.head()
df2.tail(10)
df2.info()
df2.describe()

<class 'pandas.DataFrame'>
RangeIndex: 262 entries, 0 to 261
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   title        262 non-null    str
 1   description  262 non-null    str
 2   category     262 non-null    str
 3   language     262 non-null    str
 4   actor_name   262 non-null    str
dtypes: str(5)
memory usage: 10.4 KB

,title,description,category,language,actor_name
count,262,262,262,262,262
unique,46,46,15,1,145
top,ARABIA DOGMA,A Touching Epistle of a Madman And a Mad Cow w...,Horror,English,OPRAH KILMER
freq,12,12,55,262,8

The info output shows the number of rows, columns, column names, non-null values, and data types in the dataset.

The describe output summarizes numeric columns using count, mean, standard deviation, minimum, maximum, and quartiles.

In [26]:
df3 = pd.read_csv("northwind_example.csv")

df3
df3.describe()

            OrderID   UnitPrice    Quantity
count    500.000000  500.000000  500.000000
mean   10341.364000   23.371400   24.330000
std       54.442663   27.334436   18.069702
min    10248.000000    2.000000    1.000000
25%    10294.000000   10.400000   10.000000
50%    10341.000000   15.800000   20.000000
75%    10389.000000   27.800000   32.000000
max    10436.000000  210.800000  120.000000

The describe output is useful for understanding the numeric business data in this dataset, such as totals, quantities, or prices. The results are different because this dataset contains different columns from the Sakila dataset.

In [27]:
test_data = {
    'ID': [1, 2, 3, 4, 5, 6, 7, 8],
    'Name': ['Alicia', 'Bob', 'Charlie', 'Dominic', 'Eve', 'Frank', 'Grace', 'Heidi'],
    'Age': [25, np.nan, 22, 19, 31, 35, np.nan, 18],
    'City': ['NY', 'LA', 'Chicago', 'Houston', 'Phoenix', 'Boston', 'Austin', 'San Diego'],
    'Score': [85, 92, -1, 65, 78, np.nan, 55, 90]
}

df4 = pd.DataFrame(test_data)

df4

df4.to_csv("test_data.csv", index=False)