# Exercise 2.C Working with multiple DataFrames

In [7]:
import pandas as pd

In [8]:
employees = {
    "EmployeeID": [1, 2, 3, 4],
    "Name": ["Alice", "Bob", "Charlie", "Diana"],
    "DepartmentID": [101, 102, 101, 103]
}

departments = {
    "DepartmentID": [101, 102, 103],
    "DepartmentName": ["HR", "Finance", "IT"]
}

salaries = {
    "EmployeeID": [1, 2, 3, 4],
    "Salary": [60000, 75000, 50000, 90000]
}

df_employees = pd.DataFrame(employees)
df_departments = pd.DataFrame(departments)
df_salaries = pd.DataFrame(salaries)

df_employees
df_departments
df_salaries

   EmployeeID  Salary
0           1   60000
1           2   75000
2           3   50000
3           4   90000

In [9]:
merged_df = pd.merge(df_employees, df_departments, on="DepartmentID")
merged_df

   EmployeeID     Name  DepartmentID DepartmentName
0           1    Alice           101             HR
1           2      Bob           102        Finance
2           3  Charlie           101             HR
3           4    Diana           103             IT

In [10]:
final_df = pd.merge(merged_df, df_salaries, on="EmployeeID")
final_df

   EmployeeID     Name  DepartmentID DepartmentName  Salary
0           1    Alice           101             HR   60000
1           2      Bob           102        Finance   75000
2           3  Charlie           101             HR   50000
3           4    Diana           103             IT   90000

In [11]:
high_salary = final_df[final_df["Salary"] > 60000]
high_salary

   EmployeeID   Name  DepartmentID DepartmentName  Salary
1           2    Bob           102        Finance   75000
3           4  Diana           103             IT   90000

In [12]:
grouped = final_df.groupby("DepartmentName")["Salary"].mean()
grouped

DepartmentName
Finance    75000.0
HR         55000.0
IT         90000.0
Name: Salary, dtype: float64

The merge function combines related data from different DataFrames using matching columns. Groupby helps summarize data by category, such as finding the average salary for each department.